/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "src/lib/utils.ts",
      type: "registry:lib",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/lib/utils.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "utils"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "use-copy-to-clipboard": {
    name: "use-copy-to-clipboard",
    description: "",
    type: "registry:hook",
    files: [{
      path: "src/registry/hooks/use-copy-to-clipboard/use-copy-to-clipboard.ts",
      type: "registry:hook",
      target: "@hooks/use-copy-to-clipboard.ts",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/hooks/use-copy-to-clipboard/use-copy-to-clipboard.ts")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "use-copy-to-clipboard"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stars-travel": {
    name: "stars-travel",
    description: "A motion-driven SVG background with an animated 'infinite travel' effect.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/stars-travel/stars-travel.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/stars-travel/stars-travel.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stars-travel"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "perspective-tilt": {
    name: "perspective-tilt",
    description: "A 3D card with perspective tilt and blur transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/perspective-tilt/perspective-tilt.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/perspective-tilt/perspective-tilt.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "perspective-tilt"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button": {
    name: "copy-button",
    description: "A copy button with direction-aware icon transitions.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/copy-button/copy-button.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/copy-button/copy-button.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "copy-button"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "blur-shimmer-text": {
    name: "blur-shimmer-text",
    description: "A text component that loops phrases with a horizontal blur shimmer.",
    type: "registry:component",
    files: [{
      path: "src/registry/components/blur-shimmer-text/blur-shimmer-text.tsx",
      type: "registry:component",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/components/blur-shimmer-text/blur-shimmer-text.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "blur-shimmer-text"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stars-travel-demo": {
    name: "stars-travel-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/stars-travel-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/stars-travel-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stars-travel-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "stars-travel-duration-demo": {
    name: "stars-travel-duration-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/stars-travel-duration-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/stars-travel-duration-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "stars-travel-duration-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "perspective-tilt-demo": {
    name: "perspective-tilt-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/perspective-tilt-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/perspective-tilt-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "perspective-tilt-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "copy-button-demo": {
    name: "copy-button-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/copy-button-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/copy-button-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "copy-button-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "blur-shimmer-text-demo": {
    name: "blur-shimmer-text-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "src/registry/examples/blur-shimmer-text-demo.tsx",
      type: "registry:example",
      target: "",
    }],
    component: React.lazy(async () => {
      const mod = await import("@/registry/examples/blur-shimmer-text-demo.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "blur-shimmer-text-demo"
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
}